# Generated by Django 5.1 on 2024-08-27 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_favorite', to='products.product', verbose_name='Product'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('customer', 'product')},
        ),
    ]
